apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metagate

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgresql-init-configmap.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: metagate

images:
  - name: metagate
    newTag: "0.1"
